### PR TITLE
A few refactoring if/elif/else construction

### PR DESCRIPTION
**Pull request by ivanov-dv**

### CODE REVIEW

**Comment by FlipperPA** [comment]
@ivanov-dv Thanks for the contribution. Can you give us some context on why this refactor would be necessary?

In looking at the logic, some conditions seem to just be creating unnecessary operations, such as the changes to line 92 and 94. If that `if` / `elif` block matches the first condition, why should the rest be evaluated for a value that can't be possible?

It is entirely possible I'm missing something too.

**Comment by ivanov-dv** [comment]
@FlipperPA Thanks for the answer!  
 
This refactoring is not necessary and does not affect the functionality or speed of the code. But if we use the `if / elif / else` construct, the function stops executing after `return / raise`  and transfers control to the external code. In your example, the code will not execute lines 92 and 94 if the condition on line 90 is true.

I also used the source [pylint](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/no-else-return.html), where this case is described. 

I could also possibly be missing something. I would appreciate your comments.

**Comment by browniebroke** [comment]
I don't really the point in this change to be honest, as you put it:

> This refactoring is not necessary and does not affect the functionality or speed of the code

Because of that, I would vote in favour of status-quo (don't change it).

> I also used the source [pylint](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/no-else-return.html), where this case is described.

Sure, linters are useful but this rule is very subjective IMO, reminds me of [this article from Trey Hunner](https://www.pythonmorsels.com/unnecessary-else-statements/) which does a good job at explaining why "it depends".

**Comment by ivanov-dv** [comment]
@browniebroke Thanks for the answer! I agree with you, this can be very subjective.

**Pull request closed without merging**
